# Generated by Django 4.1 on 2023-04-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
